boostcampwm-2024/and04-Nature-Album

- app/src/main/java/com/and04/naturealbum/data/repository/DataRepository.kt
- app/src/main/java/com/and04/naturealbum/data/room/DataDao.kt
- app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
- app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchScreen.kt
- app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
- app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoViewModel.kt
✅ insert명령 반환타입 추가
✅ HomeScreenViewModel추가
✅ 리스너 등록
> 사진 상세 화면에서 DB에 저장

- app/src/main/java/com/and04/naturealbum/ui/MainActivity.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
✅ 앱 시작시 익명회원으로 시작
✅ 구글계정 회원가입시 익명회원→구글 전환
✅ 기존에 존재하는 구글 계정으로 로그인시 익명계정 삭제
- 앱을 처음 빌드하고 실행시 Activity가 두번 생성되며 익명계정이 두개 생성되는 문제
→ bundle이 null일때만 익명 로그인
- 구글 계정 로그인 이후 앱을 다시 실핼할때 익명계정이 생성되는 문제
→ 현재 계정이 null일때만 익명 계정 생성
- 기존에 가입한 구글계정으로 재가입시 로그인 불가능
→ 로그인이전 현재 계정이 익명계정인지 확인
→ 현재 계정이 익명계정이거나 null일때 구글 로그인 실행
→ 익명계정일때 : 구글계정으로 전환(회원가입) 실패시 익명계정 삭제후 로그인 시도
→ null일때 : 구글계정으로 회원가입/로그인 시도
> 익명 회원 로그인 추가

- app/src/main/java/com/and04/naturealbum/di/RoomModule.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
✅ 힐트를 사용하여 MyPageViewModel, AuthenticationManager 의존성 주입
✅ AuthenticationManager 리펙토링
[AuthenticationManager 리펙토링 | 트러블 슈팅](https://github.com/boostcampwm-2024/and04-Nature-Album/wiki/AuthenticationManager_리펙토링_과정)
> AuthenticationManager 리펙토링

- app/src/main/java/com/and04/naturealbum/ui/MainActivity.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
> [Fix] 익명 로그인 삭제

- app/build.gradle.kts
- app/src/main/java/com/and04/naturealbum/ui/album/AlbumScreen.kt
- app/src/main/java/com/and04/naturealbum/ui/albumfolder/AlbumFolderScreen.kt
- app/src/main/java/com/and04/naturealbum/ui/component/ClippingButton.kt
- app/src/main/java/com/and04/naturealbum/ui/component/MyTopAppBar.kt
- app/src/main/java/com/and04/naturealbum/ui/component/NavigationImageButton.kt
- app/src/main/java/com/and04/naturealbum/ui/component/TopAppBar.kt
- app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
- app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenLandscape.kt
- app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenPortrait.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
- app/src/main/java/com/and04/naturealbum/ui/photoinfo/PhotoInfo.kt
✅ 메인 화면 
✅ 도감 화면
✅ 도감 화인 화면
✅ 사진 상세 화면
대응!!
https://github.com/user-attachments/assets/5bce44d4-dc7b-426f-9d7c-7b8418091a1c
> 메인,도감화면  configuration change 대응

- app/src/main/res/values/strings.xml
> [Fix] xml파일 구조

- app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
- 사진 저장 후 앨범으로 이동시 라벨이 초기화되지 않는 문제 해결
> [Fix] reset label

- app/src/main/java/com/and04/naturealbum/ui/labelsearch/LabelSearchScreen.kt
- app/src/main/res/values/strings.xml
> [Fix] 중복 라벨 생성 방지

- app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
- app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenLandscape.kt
- app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenPortrait.kt
- SavePhotoScreen에서 photoSaveState를 by 키워드에서 = 키워드로 수정 후 해결
- 이에 따라 파라미터 역시 State로 실제 값을 묶어서 전달하는 방식으로 수정
> [Fix] 머지 과정에서 해결하지 못한 conflict 해결

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/and04/naturealbum/NatureAlbum.kt
- app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
- app/src/main/java/com/and04/naturealbum/utils/NetworkState.kt
네트워크 연결 >> 파이어베이스 저장
네트워크 없음 >> Room에만 저장
---
네트워크 상태 확인 공식문서
https://developer.android.com/develop/connectivity/network-ops/reading-network-state?hl=ko
> 도감 등록 시 네트워크 확인

- app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
- app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
- app/src/main/java/com/and04/naturealbum/utils/NetworkState.kt
- app/src/main/res/values/strings.xml
- 이메일 하단에 동기화 UI 추가
- 네트워크 상태에 따른 SnackBar 추가
> 마이페이지에 동기화 UI 추가

- app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
✅ 클러스터에 아이템 갯수에 따른 tint 적용
✅ 클러스터 아이템 갯수 텍스트로 추가
> 클러스터 틴트 및 텍스트 추가

- app/src/main/java/com/and04/naturealbum/di/AuthenticationModule.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
- 기존 ViewModel에서 context 주입 받던 코드 삭제
- UserManager 생성자로 주입
> Hilt로 기존 코드 개선

- app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
- 마이 페이지에서 동기화 버튼 클릭 시 즉시 동기화 기능 구현
만약 이미 동기화가 진행 중 이라면 동기화 버튼을 클릭하더라도 새로 동기화를 진행하지 않도록 구현
> 즉시 동기화 기능 구현

- app/src/main/java/com/and04/naturealbum/di/AuthenticationModule.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/AuthenticationManager.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
- app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
API 33이하에서 Google Credential Context를 Hilt를 통해 주입하면 에러 발생하여 원상 복구
---
급하시면 Merge하여 Pull 받으시면 됩니다.
추가로 개선 방안이 있으시면 해당 브랜치에서 작업하여 push해주세요.
> 로그인 오류 - 이전 Hilt로 Context 주입 원상복구

- app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
- app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumDestination.kt
- app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumState.kt
- `NatureAlbumState` 상태 관리 클래스 생성
- `NatureAlbumApp` 에서 상태 분리
> NatureAlbumApp Navigation 리펙토링

- app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
- app/src/main/java/com/and04/naturealbum/data/dto/FirebaseDto.kt
- app/src/main/java/com/and04/naturealbum/data/repository/FireBaseRepository.kt
동기화 도중 라벨이 중복 될 경우 로컬 라벨로 데이터 갱신
> [동기화] 라벨 중복 시 로컬 라벨로 서버에 업데이트

- app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
- app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumState.kt
마이페이지에서 기기 자체의 뒤로가기 버튼 눌렀을 때 백스택관리 안되던 것 수정
> [Fix] 마이페이지에서 바로 홈화면 가는 것이 아닌 popBackStack으로 가도록 수정

- app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
java.lang.IllegalStateException: Launcher has not been initialized. Launcher 발생
해당 코드에서 알 수 없는 이유로 Error 발생하여 SideEffect로 감싸줘 해결
----
모두에게 생기는 문제는 아니고 일부 사용자에게 생기는 문제로 보임
> [Fix] MyPage 팅기는 오류 해결

- app/src/main/java/com/and04/naturealbum/ui/LocationHandler.kt
- app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
- app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
- app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenLandscape.kt
- app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreenPortrait.kt
https://github.com/user-attachments/assets/d7bff4b8-5316-41e8-badb-357982a50c2f
- 사진 찍고 설정 아니오 누를 시 홈으로 이동
> [Fix] 위치 꺼져 있을 때 사진 찍으면 앱 터짐

- app/src/main/java/com/and04/naturealbum/ui/LocationHandler.kt
- app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
- app/src/main/res/values/strings.xml
비행기 모드일 경우 위치 확인 시 ApiException 발생
- 위치를 얻으려면 WIFI를 연결하거나, 비행기 모드를 해제해야 한다.
- 사용자에게 Toast Message 안내
> [Fix] 비행기 모드일 때 카메라 미동작

- app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
> [Fix] 사진 저장화면 무한로딩 수정

- app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
> [Fix] 지도화면 bottom sheet 라벨 텍스트 멀티라인 제거

- app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
원인
WorkManager 등록 시 WIFI 연결 조건이 추가되어 있었다.
해결
해당 코드 제거
> 데이터 상태에서 수동 동기화 미작동
